### ISSUE TITLE
Local build does not work

### ISSUE THREAD

**Issue by matthiasfahrni** [avenqo/cucumber4eclipse#1]
## Summary
Second step of the described building procedure does not work

## Expected Behavior
mav build finishes successfully

## Current Behavior
i try to build cucmber4eclispe following the build description:

- checkout (master)
- mvn clean install org.reficio:p2-maven-plugin:1.3.0:site -f pom_swtbot.xml
 --> ok
- cd cucumber-eclipse
- **mvn clean verify**
 --> results the following error message:

....
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops/R20181128170323/repository/
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops/R20181128170323/repository/
[INFO] Adding repository http://download.eclipse.org/tools/orbit/downloads/drops/R20181128170323/repository
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops2/R20181128170323/repository/
[INFO] Fetching p2.index from http://download.eclipse.org/tools/orbit/downloads/drops2/R20181128170323/repository/
[INFO] Resolving dependencies of MavenProject: io.cucumber:io.cucumber.core.eclipse:4.2.1-SNAPSHOT @ C:\dev\projects\cucumber4eclipse\cucumber-eclipse\bundles\core-eclipse\pom.xml
[INFO] {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: io.cucumber.core.eclipse 4.2.1.qualifier
[ERROR]   Missing requirement: io.cucumber.core.eclipse 4.2.1.qualifier requires 'osgi.bundle; io.cucumber.core 4.2.1' but it could not be found
[ERROR]
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: io.cucumber:io.cucumber.core.eclipse:4.2.1-SNAPSHOT @ C:\dev\projects\cucumber4eclipse\cucumber-eclipse\bundles\core-eclipse\pom.xml: See log for details -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException

After the first mvn call the content of "cucumber4eclipse/distribution-p2/target/repository/plugins" is

-rw-r--r-- 1 myuser 1049089  546131 Jul  4 20:20 io.cucumber.core_4.2.1.20190704202043.jar
-rw-r--r-- 1 myuser 1049089   26862 Jul  4 20:20 io.cucumber.datatable.source_1.1.7.jar
-rw-r--r-- 1 myuser 1049089   61495 Jul  4 20:20 io.cucumber.datatable_1.1.7.jar
-rw-r--r-- 1 myuser 1049089 1497087 Jul  4 20:20 io.cucumber.datatable-dependencies.source_1.1.7.jar
-rw-r--r-- 1 myuser 1049089 1861707 Jul  4 20:20 io.cucumber.datatable-dependencies_1.1.7.jar
-rw-r--r-- 1 myuser 1049089   26148 Jul  4 20:20 io.cucumber.expressions.source_6.2.0.jar
-rw-r--r-- 1 myuser 1049089   53383 Jul  4 20:20 io.cucumber.expressions_6.2.0.jar
-rw-r--r-- 1 myuser 1049089   45180 Jul  4 20:20 io.cucumber.gherkin.source_5.1.0.jar
-rw-r--r-- 1 myuser 1049089  342077 Jul  4 20:20 io.cucumber.gherkin_5.1.0.jar
-rw-r--r-- 1 myuser 1049089   55497 Jul  4 20:20 io.cucumber.html.source_0.2.7.jar
-rw-r--r-- 1 myuser 1049089   39350 Jul  4 20:20 io.cucumber.html_0.2.7.jar
-rw-r--r-- 1 myuser 1049089  340185 Jul  4 20:20 io.cucumber.java_4.2.1.20190704202043.jar
-rw-r--r-- 1 myuser 1049089   34514 Jul  4 20:20 io.cucumber.junit_4.2.1.20190704202043.jar
-rw-r--r-- 1 myuser 1049089    3246 Jul  4 20:20 io.cucumber.tag-expressions.source_1.1.1.jar
-rw-r--r-- 1 myuser 1049089   14631 Jul  4 20:20 io.cucumber.tag-expressions_1.1.1.jar
-rw-r--r-- 1 myuser 1049089  204185 Jul  4 20:20 junit.source_4.12.0.jar
-rw-r--r-- 1 myuser 1049089  320786 Jul  4 20:20 junit_4.12.0.jar
-rw-r--r-- 1 myuser 1049089   33378 Jul  4 20:20 org.hamcrest.core.source_1.3.0.jar
-rw-r--r-- 1 myuser 1049089   45892 Jul  4 20:20 org.hamcrest.core_1.3.0.jar

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
Follow the building instructions. The error occurs while executing step 4 (mvn clean verify)

## Context & Motivation
I would like to use the io.cucumber OSGi bundles for our cucumber tests, developed ineclipse and executed in Jenkins

## Your Environment
$ mvn -version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: C:\dev\eaio-ng\maven\3.6
Java version: 1.8.0_151-1-ojdkbuild, vendor: Oracle Corporation, runtime: C:\dev\eaio-ng\jdk\openjdk8\jre
Default locale: de_CH, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by avenqo** [comment]
Source module was missing. Fixed.
